env:
  browser: true
  commonjs: true
  es6: true
  mocha: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
      jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
parser: babel-eslint
  
rules:
  "indent": 2
  "react-hooks/rules-of-hooks": 2
  "react-hooks/exhaustive-deps": 1
  "quotes": [1, "single", "avoid-escape"]
  "semi": [2,"always"]
  "no-undef": 2
